New API, using REST instead of DRb
Change-Id: I57c851b71fcb3857e06eca744281d7922b721540

diff --git a/addons/rc/debian/kadeploy3d b/addons/rc/debian/kadeploy3d
--- a/addons/rc/debian/kadeploy3d
+++ b/addons/rc/debian/kadeploy3d
@@ -20,9 +20,10 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 DESC="Kadeploy Server"
 NAME=kadeploy3d
 DAEMON=/usr/sbin/$NAME
-DAEMON_ARGS=
 PIDFILE=/var/run/$NAME.pid
+DAEMON_ARGS="--pidfile $PIDFILE --detach"
 SCRIPTNAME=/etc/init.d/$NAME
+DAEMON_USER=deploy
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -47,13 +48,14 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-        [ -e $PIDFILE ] && [ -e /proc/`cat $PIDFILE` ] && echo "Daemon already running" && return 1
-        start-stop-daemon --start --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON --test -- $DAEMON_ARGS > /dev/null || return 1
-        start-stop-daemon --start --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid deploy -- $DAEMON_ARGS || return 2
+        [ -e $PIDFILE ] && [ -e /proc/`cat $PIDFILE` ] && return 1
+        [ -e $PIDFILE ] || ( touch $PIDFILE && chown $DAEMON_USER:$DAEMON_USER $PIDFILE )
+        start-stop-daemon --start --quiet --exec $DAEMON --test -- $DAEMON_ARGS > /dev/null || return 1
+        start-stop-daemon --start --quiet --exec $DAEMON --chuid $DAEMON_USER -- $DAEMON_ARGS > /dev/null || return 2
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
-	sleep 5; [ -e /proc/`cat $PIDFILE` ] || (rm $PIDFILE ;return 2)
+	sleep 1 && [ -e /proc/`cat $PIDFILE` ] || (rm $PIDFILE ;return 2)
 }
 
 #
@@ -87,8 +89,9 @@ case "$1" in
 	log_action_begin_msg "Starting $DESC"
 	do_start
 	case "$?" in
-		0|1) log_action_end_msg 0 ;;
-		2) log_action_end_msg 1; log_daemon_msg "An error occured, probably a configuration issue, please check your syslog file." ;;
+		0) log_action_end_msg 0 ;;
+		1) log_action_end_msg 1 ; echo "Daemon already running" 1>&2;;
+		2) log_action_end_msg 1;; #log_daemon_msg "An error occured, probably a configuration issue, please check your syslog file." ;;
 	esac
 	;;
   stop)
@@ -108,7 +111,7 @@ case "$1" in
 		case "$?" in
 			0) log_action_end_msg 0 ;;
 			1) log_action_end_msg 1 ;; # Old process is still running
-			*) log_action_end_msg 1; log_daemon_msg "An error occured, probably a configuration issue, please check your syslog file." ;; # Failed to start
+			*) log_action_end_msg 1;; # log_daemon_msg "An error occured, probably a configuration issue, please check your syslog file." ;; # Failed to start
 		esac
 		;;
 	  *)
