Improved the Debian init script

diff --git a/addons/rc/debian/kadeploy b/addons/rc/debian/kadeploy
--- a/addons/rc/debian/kadeploy
+++ b/addons/rc/debian/kadeploy
@@ -102,26 +102,28 @@ do_reload()
 	sed '1d' $RUNDIR/reload >&2
 	return 0
 }
-
+EXITSTATUS=0
 case "$1" in
   start)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0) [ "$VERBOSE" != no ] && log_end_msg 0;;
+		1) EXITSTATUS=1 && [ "$VERBOSE" != no ] && log_end_msg 0;;
+		2) EXITSTATUS=2 && [ "$VERBOSE" != no ] && log_end_msg 1;;
 	esac
 	;;
   stop)
 	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		0) [ "$VERBOSE" != no ] && log_end_msg 0;;
+		1) EXITSTATUS=1 && [ "$VERBOSE" != no ] && log_end_msg 0;;
+		2) EXITSTATUS=2 && [ "$VERBOSE" != no ] && log_end_msg 1;;
 	esac
 	;;
   status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	status_of_proc "$DAEMON" "$NAME" || EXITSTATUS=$?
 	;;
   reload|force-reload)
 	log_daemon_msg "Reloading $DESC" "$NAME"
@@ -135,21 +137,20 @@ case "$1" in
 	  0|1)
 		do_start
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			0) log_end_msg 0;;
+			1) EXITSTATUS=1 && log_end_msg 1;; # Old process is still running
+			*) EXITSTATUS=2 && log_end_msg 1;; # Failed to start
 		esac
 		;;
 	  *)
 		# Failed to stop
-		log_end_msg 1
+		EXITSTATUS=2 && log_end_msg 1
 		;;
 	esac
 	;;
   *)
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
-	exit 3
+	EXITSTATUS=3
 	;;
 esac
-
-:
+exit $EXITSTATUS
