Bugfix: changed a condition in init scripts that may fail on some environments
Change-Id: Ic5eef236a11e0d7bdadc69088a5cfaf01824941c

diff --git a/addons/rc/fedora/kadeploy3d b/addons/rc/fedora/kadeploy3d
--- a/addons/rc/fedora/kadeploy3d
+++ b/addons/rc/fedora/kadeploy3d
@@ -32,7 +32,7 @@ start() {
 	PID=`pidof -x $kadeploy3d`
 	echo ${PID} > ${pidfile}
         echo
-	( [ $PID ] && [ -x /proc/${PID} ] ) || (echo ""; echo "An error occured, probably a configuration issue, please check your syslog file." ; rm ${pidfile} ; return 1)
+	( [ -n "$PID" ] && [ -x /proc/${PID} ] ) || (echo ""; echo "An error occured, probably a configuration issue, please check your syslog file." ; rm ${pidfile} ; return 1)
 	[ $RETVAL = 0 ] && touch ${lockfile}
         return $RETVAL
 }
